version: 2

jobs:
  "python-2.7": &test-template
    docker:
      - image: circleci/python:2.7-stretch-browsers
        environment:
          REQUIREMENTS_FILE: .circleci/requirements/dev-requirements.txt
          PYLINTRC: .pylintrc

    steps:
      - checkout

      - run:
          name: Write deps cache key
          command: cat "$REQUIREMENTS_FILE" > reqs.txt

      - run:
          name: Write job name
          command: echo $CIRCLE_JOB > circlejob.txt

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "reqs.txt" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "circlejob.txt" }}

      - run:
          name: Install dependencies
          command: |
              sudo pip install virtualenv
              virtualenv venv
              . venv/bin/activate
              pip install -r $REQUIREMENTS_FILE

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "reqs.txt" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "circlejob.txt" }}
          paths:
              - "venv"

      - run:
          name: Run lint
          command: |
              . venv/bin/activate
              pylint dash setup.py --rcfile=$PYLINTRC
              pylint tests -d all -e C0102,C0112,C0121,C0202,C0203,C0204,C0304,C0321,C0325,C0410,C0411,C0412,C0413,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0106,E0107,E0108,E0202,E0203,E0211,E0221,E0222,E0235,E0601,E0602,E0603,E0604,E0611,E0701,E0702,E0710,E0711,E0712,W0109
              flake8 dash setup.py
              flake8 --ignore=E123,E126,E501,E722,E731,F401,F841,W503,W504 --exclude=metadata_test.py tests

      - run:
          name: Run tests
          command: |
              . venv/bin/activate
              python --version
              python -m unittest tests.development.test_base_component
              python -m unittest tests.development.test_component_loader
              python -m unittest tests.test_integration
              python -m unittest tests.test_resources
              python -m unittest tests.test_configs

  "python-3.6":
    <<: *test-template
    docker:
      - image: circleci/python:3.6-stretch-browsers
        environment:
          REQUIREMENTS_FILE: .circleci/requirements/dev-requirements.txt
          PYLINTRC: .pylintrc
          PERCY_ENABLE: 0

  "python-3.7":
    <<: *test-template
    docker:
      - image: circleci/python:3.7-stretch-browsers
        environment:
          REQUIREMENTS_FILE: .circleci/requirements/dev-requirements-py37.txt
          PYLINTRC: .pylintrc37
          PERCY_ENABLE: 0


workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.6"
      - "python-3.7"